CLASS zcl_fabap_jul2025_demo05_eat2 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun .
*  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_FABAP_JUL2025_DEMO05_EAT2 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    out->write( |Hello World!| ).

  ENDMETHOD.
ENDCLASS.
